version: '3.9'
# Add envs to push!
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbpara
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql